## Fragment for catalog items
fragment CatalogCommon on Catalog {
  pageInfo {
    hasNextPage
    endCursor
  }
  edges {
    node {
      id
      createdAt
      isBackorder
      isLowQuantity
      isSoldOut
      metafields {
        value
        key
      }
      shopId
    }
  }
}
