query productSearch($query: String!) {
  productSearch(query: {match: {product__title: {query: $query}}}) {
    hits {
      _source {
        id
        shopId
        product {
          title
          description
        }
      }
    }
  }
}
