#import "./fragments.gql"

# Get an order
query catalogBySearch($shopId: ID!, $token: String, $query: String) {
  results: catalogBySearch(shopId: $shopId, token: $token, query: $query) {
    ...CatalogCommon
  }
}
